name: ModifyDropRate
version: 1.0-SNAPSHOT
main: io.github.tinypot.tweaks.mdr.ModifyDropRatePlugin
author: tinypot
api-version: 1.18

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.21
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.3
  - io.github.monun:kommand-core:2.12.0